name: Random Signals
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2056441493332386
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#cccccc'
    - '#2a2a2a'
    - '#505050'
    - '#f2f2f2'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.47156102396547794
  rhythmicContrast: 0.75
purpose: []
