name: Random Signals
favicon: null
layout_spectrum: 0.857668339740485
typography_spectrum: 0.2056441493332386
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.47156102396547794
  rhythmicContrast: 0.75
purpose: []
